### PR TITLE
Fixing footer social links

### PR DESCRIPTION
**Pull request by kempsterrrr**
This PR address #9 

- corrects twitter url
- corrects Github url

@gordo-labs how do we update the logo for Twitter? Looks like it's coming from another library you've created so wasn't sure how to update it

```javascript

import {
  ArrowTopRightIcon,
  Body1,
  Body3,
  DDLogoIcon,
  GithubIcon,
  TwitterIcon,
  YoutubeIcon,
} from '@gordo-d/d-d-ui-components';

```

### CODE REVIEW

**Comment by gordo-labs** [comment]
> This PR address #9
> 
> * corrects twitter url
> * corrects Github url
> 
> @gordo-labs how do we update the logo for Twitter? Looks like it's coming from another library you've created so wasn't sure how to update it
> 
> ```js
> import {
>   ArrowTopRightIcon,
>   Body1,
>   Body3,
>   DDLogoIcon,
>   GithubIcon,
>   TwitterIcon,
>   YoutubeIcon,
> } from '@gordo-d/d-d-ui-components';
> ```

It is the design-system. Which indeed would be interesting to start collaborating within the active projects in the DAO. Academy + RPC
[D_D Design System](https://github.com/Developer-DAO/design-system)

**Comment by kempsterrrr** [comment]
Thanks @gordo-labs - I'm not exactly what the workflow is here for making these changes but have opened a PR in the design system to update the logo to the X logo [here](https://github.com/Developer-DAO/design-system/pull/1).

Can you let me know what I need to do from here please?

**Comment by kempsterrrr** [comment]
> It is the design-system. Which indeed would be interesting to start collaborating within the active projects in the DAO. Academy + RPC
> [D_D Design System](https://github.com/Developer-DAO/design-system)

As for active project collaborating on a shared design system in principal I like the idea though these projects are already decently along their own journeys so unclear if they'd be up for that at this stage.

Academy has their own component library going - https://github.com/Developer-DAO/academy-turbo cc @wolovim @markkos89

Looks like RPC are building fresh components - https://github.com/Developer-DAO/ddrpc-frontend - cc @vorcigernix @PSkinnerTech

**Comment by gordo-labs** [comment]
> > It is the design-system. Which indeed would be interesting to start collaborating within the active projects in the DAO. Academy + RPC
> > [D_D Design System](https://github.com/Developer-DAO/design-system)
> 
> As for active project collaborating on a shared design system in principal I like the idea though these projects are already decently along their own journeys so unclear if they'd be up for that at this stage.
> 
> Academy has their own component library going - https://github.com/Developer-DAO/academy-turbo cc @wolovim @Markkos89
> 
> Looks like RPC are building fresh components - https://github.com/Developer-DAO/ddrpc-frontend - cc @vorcigernix @PSkinnerTech

If you guys are interested we can sort out something cohesive for D_D as a whole. The framework to use all the components it is already in place.
We can publish the NPM package as @d_d/ui-components

**Comment by gordo-labs** [comment]
> Thanks @gordo-labs - I'm not exactly what the workflow is here for making these changes but have opened a PR in the design system to update the logo to the X logo [here](https://github.com/Developer-DAO/design-system/pull/1).
> 
> Can you let me know what I need to do from here please?

The process is adding the icon to ui-components to be able to be added as a React Component to any place within the import, and that's it.

**Pull request merged**
